theme: minima
title: Vikranth Kattakuri
author: Vikranth
email: vikranthiit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mechatronics Engineer at Flexiv. 
  Masters in Mechanical Engineering from Purdue University.

# social links
github_username:  vikranth16 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
